name: "C1 rw-bad-main"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - trigger.txt
permissions:
  contents: read
jobs:
  case:
    uses: naylorb/sb-lib/.github/workflows/rw-bad.yml@main
