name: "D2 local-dollar"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - trigger.txt
permissions:
  contents: read
jobs:
  case:
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/local
